// Mock Data Layer for Vibelearn
// Faithful to Supabase PostgreSQL schema and UI designs

export const MOCK_COURSES = [
  {
    id: 'course-1',
    title: 'Next.js for Production',
    slug: 'nextjs-for-production',
    summary:
      'Build scalable, high-performance web applications with Next.js, best practices, and production-ready deployment strategies.',
    level: 'Intermediate',
    duration: '18h 24m',
    students: '3,426',
    modulesCount: 12,
    badge: 'Popular',
    tagType: 'popular',
    iconType: 'nextjs',
    accentColor: '#10B981',
    progress: 35,
    coverImageUrl:
      'https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&w=800&q=80',
    whatYoullLearn: [
      {
        id: 'wyl-1',
        title: 'App Router Foundations',
        description: 'Master the App Router, layouts, loading states, and nested routing.',
        icon: 'layers',
      },
      {
        id: 'wyl-2',
        title: 'Data Fetching & Caching',
        description: 'Fetch data efficiently and leverage caching for better performance.',
        icon: 'database',
      },
      {
        id: 'wyl-3',
        title: 'Performance Optimization',
        description: 'Optimize rendering, assets, and bundle size for faster apps.',
        icon: 'gauge',
      },
      {
        id: 'wyl-4',
        title: 'Deployment & Scaling',
        description: 'Deploy with confidence and scale your Next.js applications.',
        icon: 'cloud',
      },
    ],
    modules: [
      {
        id: 'mod-1',
        position: 1,
        title: 'Introduction to Next.js',
        summary: "Understand the core features of Next.js and why it's the React framework.",
        duration: '45m',
        isCompleted: true,
        lessons: [
          {
            id: 'les-1-1',
            slug: 'welcome-to-nextjs',
            title: 'Welcome to the Course',
            duration: '15m',
            youtubeVideoId: 'SqcY0GlETPk',
            isCompleted: true,
          },
          {
            id: 'les-1-2',
            slug: 'architecture-overview',
            title: 'Next.js Architecture Overview',
            duration: '30m',
            youtubeVideoId: '843nec-IvW0',
            isCompleted: true,
          },
        ],
      },
      {
        id: 'mod-2',
        position: 2,
        title: 'Project Setup & Structure',
        summary: 'Set up a new Next.js project and explore the folder structure.',
        duration: '1h 12m',
        isCompleted: true,
        lessons: [
          {
            id: 'les-2-1',
            slug: 'scaffolding-project',
            title: 'Scaffolding with create-next-app',
            duration: '30m',
            youtubeVideoId: 'wm5gMKuwSYk',
            isCompleted: true,
          },
          {
            id: 'les-2-2',
            slug: 'folder-conventions',
            title: 'Folder Conventions and App Router Structure',
            duration: '42m',
            youtubeVideoId: 'ZVnjOPwW4ZA',
            isCompleted: true,
          },
        ],
      },
      {
        id: 'mod-3',
        position: 3,
        title: 'Routing & Layouts',
        summary: 'Learn about file-based routing, layouts, and nested routes.',
        duration: '1h 36m',
        isCompleted: true,
        lessons: [
          {
            id: 'les-3-1',
            slug: 'file-based-routing',
            title: 'File-based Routing in App Router',
            duration: '48m',
            youtubeVideoId: 'vwSlYG7hFk0',
            isCompleted: true,
          },
          {
            id: 'les-3-2',
            slug: 'nested-layouts',
            title: 'Nested Layouts & Templates',
            duration: '48m',
            youtubeVideoId: 'gSSsZReIFRk',
            isCompleted: true,
          },
        ],
      },
      {
        id: 'mod-4',
        position: 4,
        title: 'Server Components',
        summary: 'Build components with server-side rendering and data fetching.',
        duration: '1h 42m',
        isCompleted: true,
        lessons: [
          {
            id: 'les-4-1',
            slug: 'rsc-deep-dive',
            title: 'React Server Components Paradigm',
            duration: '50m',
            youtubeVideoId: 'T8v37u7n4ms',
            isCompleted: true,
          },
          {
            id: 'les-4-2',
            slug: 'streaming-suspense',
            title: 'Streaming UI with Suspense and loading.js',
            duration: '52m',
            youtubeVideoId: '76z0j3BEp08',
            isCompleted: true,
          },
        ],
      },
      {
        id: 'mod-5',
        position: 5,
        title: 'Data Fetching & Caching',
        summary: 'Fetch data efficiently and leverage caching for better performance.',
        duration: '1h 28m',
        isCompleted: false,
        isActive: true,
        lessons: [
          {
            id: 'les-5-1',
            slug: 'data-fetching-caching',
            title: 'Data Fetching & Caching',
            duration: '1h 28m',
            resumeTimestamp: 765, // 12m 45s
            youtubeVideoId: 'VBlF3WVQ62Q',
            isCompleted: false,
            badge: 'LESSON 5.1',
            subtitle:
              'Learn how Next.js handles data fetching and caching in both Server and Client Components.',
            overview:
              "In this lesson, you'll learn how Next.js handles data fetching and caching in both Server and Client Components. We'll explore different caching strategies and revalidation techniques to build fast and scalable applications.",
            notes:
              '### Key Concepts\n- **fetch() API Extension**: Next.js extends standard web fetch with caching options (`cache: "force-cache"`, `next: { revalidate: 3600 }`).\n- **Request Memoization**: Repeated identical requests within the same render tree are automatically deduped.\n- **Data Cache**: Persistent server cache across incoming user requests.\n- **Full Route Cache**: Automatically renders and caches static routes at build/revalidation time.',
            takeaways: [
              'Understand the different data fetching methods in Next.js',
              'Learn how caching works in Server Components',
              'Implement revalidation and cache control',
              'Optimize performance with advanced caching strategies',
            ],
            proTip:
              'Use caching and revalidation wisely to ensure your app stays fast and data remains fresh without unnecessary requests.',
            resources: [
              {
                id: 'res-1',
                title: 'Next.js Data Fetching Documentation',
                subtitle: 'Official Next.js docs on data fetching methods.',
                link: 'https://nextjs.org/docs/app/building-your-application/data-fetching',
              },
              {
                id: 'res-2',
                title: 'Caching and Revalidation Guide',
                subtitle: 'Deep dive into Next.js caching strategies.',
                link: 'https://nextjs.org/docs/app/building-your-application/caching',
              },
              {
                id: 'res-3',
                title: 'Example Repository',
                subtitle: 'Explore the source code for this lesson.',
                link: 'https://github.com/vercel/next.js',
              },
            ],
          },
          {
            id: 'les-5-2',
            slug: 'fetching-server-components',
            title: 'Fetching in Server Components',
            duration: '21m',
            youtubeVideoId: 'O6v_Vq3s5nQ',
            isCompleted: false,
          },
          {
            id: 'les-5-3',
            slug: 'caching-strategies',
            title: 'Caching Strategies',
            duration: '23m',
            youtubeVideoId: 'e2q5yQW4Q4Y',
            isCompleted: false,
          },
          {
            id: 'les-5-4',
            slug: 'revalidation-cache-control',
            title: 'Revalidation & Cache Control',
            duration: '18m',
            youtubeVideoId: 'd5x0JCb2eAI',
            isCompleted: false,
          },
          {
            id: 'les-5-5',
            slug: 'hands-on-caching',
            title: 'Hands-on: Implement Caching',
            duration: '26m',
            youtubeVideoId: 'Sklc_fQBmcs',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'mod-6',
        position: 6,
        title: 'Authentication',
        summary: 'Implement authentication using NextAuth.js or Clerk in your app.',
        duration: '1h 18m',
        isCompleted: false,
        lessons: [
          {
            id: 'les-6-1',
            slug: 'clerk-auth-integration',
            title: 'Modern Clerk Authentication Setup',
            duration: '45m',
            youtubeVideoId: '76z0j3BEp08',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'mod-7',
        position: 7,
        title: 'API Routes & Handlers',
        summary: 'Build REST and Route Handlers for server-side processing.',
        duration: '1h 26m',
        isCompleted: false,
        lessons: [],
      },
      {
        id: 'mod-8',
        position: 8,
        title: 'Middleware & Edge Functions',
        summary: 'Inspect requests and run logic before route matching on the edge.',
        duration: '1h 10m',
        isCompleted: false,
        lessons: [],
      },
      {
        id: 'mod-9',
        position: 9,
        title: 'Performance Optimization',
        summary: 'Optimize images, scripts, fonts, and core web vitals.',
        duration: '1h 34m',
        isCompleted: false,
        lessons: [],
      },
      {
        id: 'mod-10',
        position: 10,
        title: 'Deployment on Vercel',
        summary: 'Configure CI/CD, production environments, and preview deployments.',
        duration: '56m',
        isCompleted: false,
        lessons: [],
      },
      {
        id: 'mod-11',
        position: 11,
        title: 'Monitoring & Logging',
        summary: 'Track runtime errors, performance metrics, and telemetry in production.',
        duration: '1h 8m',
        isCompleted: false,
        lessons: [],
      },
      {
        id: 'mod-12',
        position: 12,
        title: 'Best Practices & Next Steps',
        summary: 'Review production checklist, security hardening, and future roadmap.',
        duration: '52m',
        isCompleted: false,
        lessons: [],
      },
    ],
  },
  {
    id: 'course-2',
    title: 'Docker Essentials',
    slug: 'docker-essentials',
    summary:
      'Containerize applications and streamline your development workflow with modern container runtimes.',
    level: 'Beginner',
    duration: '10h 12m',
    students: '1.8k',
    modulesCount: 8,
    badge: 'Popular',
    tagType: 'popular',
    iconType: 'docker',
    accentColor: '#0EA5E9',
    progress: 60,
    coverImageUrl:
      'https://images.unsplash.com/photo-1605745341112-85968b19335b?auto=format&fit=crop&w=800&q=80',
    whatYoullLearn: [
      {
        id: 'docker-1',
        title: 'Containers vs Virtual Machines',
        description: 'Understand container isolation, layers, and daemon architecture.',
        icon: 'layers',
      },
      {
        id: 'docker-2',
        title: 'Dockerfile Mastery',
        description: 'Write multi-stage Dockerfiles optimized for size and security.',
        icon: 'database',
      },
      {
        id: 'docker-3',
        title: 'Docker Compose',
        description: 'Orchestrate multi-container microservices with networking and volumes.',
        icon: 'gauge',
      },
      {
        id: 'docker-4',
        title: 'Production Deployment',
        description: 'Deploy containers to cloud providers with restart policies and health checks.',
        icon: 'cloud',
      },
    ],
    modules: [
      {
        id: 'doc-mod-1',
        position: 1,
        title: 'Container Fundamentals',
        summary: 'What are containers, images, and registries?',
        duration: '1h 15m',
        isCompleted: true,
        lessons: [
          {
            id: 'doc-les-1',
            slug: 'intro-to-docker',
            title: 'Introduction to Docker',
            duration: '25m',
            youtubeVideoId: 'fqMOX6JJhGo',
            isCompleted: true,
          },
        ],
      },
      {
        id: 'doc-mod-2',
        position: 2,
        title: 'Writing Dockerfiles',
        summary: 'Creating reproducible container images from scratch.',
        duration: '1h 45m',
        isCompleted: true,
        lessons: [
          {
            id: 'doc-les-2',
            slug: 'building-images',
            title: 'Building and Tagging Images',
            duration: '35m',
            youtubeVideoId: 'pTFZFxd4hOI',
            isCompleted: true,
          },
        ],
      },
    ],
  },
  {
    id: 'course-3',
    title: 'TypeScript Deep Dive',
    slug: 'typescript-deep-dive',
    summary:
      'Go beyond the basics and write safer, more expressive code with advanced types, generics, and compiler options.',
    level: 'Intermediate',
    duration: '14h 36m',
    students: '2.5k',
    modulesCount: 10,
    badge: 'Trending',
    tagType: 'trending',
    iconType: 'typescript',
    accentColor: '#3B82F6',
    progress: 20,
    coverImageUrl:
      'https://images.unsplash.com/photo-1516116211227-bbc154562c14?auto=format&fit=crop&w=800&q=80',
    whatYoullLearn: [
      {
        id: 'ts-1',
        title: 'Advanced Type System',
        description: 'Union types, intersections, conditional types, and template literals.',
        icon: 'layers',
      },
      {
        id: 'ts-2',
        title: 'Generics & Utility Types',
        description: 'Create powerful, reusable generic interfaces and functions.',
        icon: 'database',
      },
      {
        id: 'ts-3',
        title: 'Strict Mode & tsconfig',
        description: 'Configure compiler options for ultimate type safety.',
        icon: 'gauge',
      },
      {
        id: 'ts-4',
        title: 'Type Narrowing & Guards',
        description: 'Write robust runtime checks with discriminative unions.',
        icon: 'cloud',
      },
    ],
    modules: [
      {
        id: 'ts-mod-1',
        position: 1,
        title: 'TypeScript Type System Fundamentals',
        summary: 'Primitive types, structural typing, and inference.',
        duration: '1h 20m',
        isCompleted: true,
        lessons: [
          {
            id: 'ts-les-1',
            slug: 'structural-typing',
            title: 'Structural Typing in Depth',
            duration: '30m',
            youtubeVideoId: 'ahCwqrYqo9o',
            isCompleted: true,
          },
        ],
      },
    ],
  },
];

export const MOCK_SEARCH_RESULTS = [
  {
    id: 'sr-1',
    type: 'video',
    courseSlug: 'nextjs-for-production',
    courseTitle: 'Next.js for Production',
    courseIcon: 'nextjs',
    lessonSlug: 'data-fetching-caching',
    title: 'Data Fetching in Server Components',
    description:
      'Learn how to fetch data on the server using async/await and Next.js best practices for better performance.',
    duration: '12:45',
    lessonNumber: 'Lesson 5.1',
    moduleName: 'Data Fetching & Caching',
    actionText: 'Watch from 12:45',
    thumbnail: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'sr-2',
    type: 'video',
    courseSlug: 'react-complete-guide',
    courseTitle: 'React Complete Guide',
    courseIcon: 'react',
    lessonSlug: 'fetching-with-use-effect',
    title: 'Fetching Data with useEffect',
    description:
      'Understand how to fetch data in React components using useEffect and handle loading states, errors, and cleanup.',
    duration: '08:32',
    lessonNumber: 'Lesson 7.2',
    moduleName: 'Data Fetching & Caching',
    actionText: 'Watch from 08:32',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'sr-3',
    type: 'video',
    courseSlug: 'docker-essentials',
    courseTitle: 'Node.js Backend Mastery',
    courseIcon: 'nodejs',
    lessonSlug: 'rest-api-fetching',
    title: 'Building REST API & Fetching Data',
    description:
      'Create REST API endpoints and learn how clients fetch and consume data effectively.',
    duration: '15:18',
    lessonNumber: 'Lesson 3.4',
    moduleName: 'API & Data Handling',
    actionText: 'Watch from 15:18',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'sr-4',
    type: 'lesson',
    courseSlug: 'nextjs-for-production',
    courseTitle: 'Next.js for Production',
    courseIcon: 'nextjs',
    lessonSlug: 'data-fetching-caching',
    title: 'Data Fetching & Caching',
    description:
      'Explore different data fetching methods in Next.js and how to cache and revalidate data for optimal performance.',
    bullets: ['Fetching strategies', 'Caching techniques', 'Revalidation methods'],
    moduleName: 'Module 5',
    actionText: 'View lesson',
  },
  {
    id: 'sr-5',
    type: 'lesson',
    courseSlug: 'react-complete-guide',
    courseTitle: 'React Complete Guide',
    courseIcon: 'react',
    lessonSlug: 'fetching-data-react',
    title: 'Fetching Data in React',
    description:
      'Learn multiple ways to fetch data in React applications and handle different states.',
    bullets: ['Fetch with fetch API', 'Axios in fetch', 'Error handling'],
    moduleName: 'Module 7',
    actionText: 'View lesson',
  },
  {
    id: 'sr-6',
    type: 'video',
    courseSlug: 'typescript-deep-dive',
    courseTitle: 'JavaScript Fundamentals',
    courseIcon: 'javascript',
    lessonSlug: 'fetch-api-basics',
    title: 'Fetch API Basics',
    description:
      'Introduction to the Fetch API, Promises, and handling JSON data in modern JavaScript.',
    duration: '06:41',
    lessonNumber: 'Lesson 4.3',
    moduleName: 'Promises & Async/Await',
    actionText: 'Watch from 06:41',
    thumbnail: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=600&q=80',
  },
];
